### ISSUE TITLE
Duplicate entries in BOTMETA after migration

### ISSUE THREAD

**Issue by mkrizek** [ansible-community/collection_migration#128]
The original BOTMETA contains:
```
  $plugins/callback/default:
    support: core
```

after migration where we migrate `lib/ansible/plugins/callback/default.py` we don't amend the existing entry but add a duplicate:

```
  lib/ansible/plugins/callback/default.py:
    migrated_to: yum_ns.yum_collection
```

Note that the original does not contain `.py` file extension which might be the reason we add a duplicate.

**Comment by bcoca** [comment]
also we don't use the $plugins macro

**Comment by webknjaz** [comment]
Looks like the problem is that we don't inject macro there..

**Comment by webknjaz** [comment]
Interesting... there's a few places in the original BOTMETA that contain things like `$plugins/callback/default` *without* `.py` ending.

*/me is curious if the bot knows to add those file extensions...*

**Comment by gundalow** [comment]
Ansibulbot adds a `*` to the end of filenames 
ie `win_command` will match `win_command.ps1` and `win_command.py`

**Comment by bcoca** [comment]
that should be fine for most cases in which we are dealing with files, directories on the other hand ...

**Comment by bcoca** [comment]
so 2 things from this:
  - need to support/resolve botmeta macros (download and use ansibullbot code?)
  - need to decide to be explicit on extensions or not, then match existing entries and update or delete and create new ones.

**Comment by gundalow** [comment]
Ansible-bot is pip installable

Extensionless is often used for Windows

>
> .
>

**Comment by bcoca** [comment]
@gundalow for doc you don't need ps1 extensions since they only support .py , afaik current doc doesn't require knowing .py extension either right now. i'll check with doc team to see if they changed that since most of their pages are currently based on 'plugin_type/plugin_name_wo_extension' with modules being a bit diff but same principle, you dont have  win_command.py and win_command.ps1 pages, just a win_commaind_module.html one.

**Comment by abadger** [comment]
Note that, the resolution of this must create per-file entries as that issue had been lumped in with this one

**Comment by bcoca** [comment]
@abadger those are already created and yes, the resolution should preserve them. 

The issue is about existing entries (which use globing) overlap with the new per file ones we add, which can be obscured as the globbing match first.  

As for a resolution, if there is a firm decision on `git rm` the files, it might even make sense to not use BOTMETA and just create this list in a migrated file to avoid conflict, the main reason BOTMETA was used initially was because keeping the files (or stubs) in core would require ansibulbot to still deal with them, but once they are removed it becomes a lot simpler.  The only other direction I see is actually using ansibullbot itself in the parsing/rewriting of the file as we process the scenarios.

**Comment by abadger** [comment]
I've talked with @mkrizek on slack and he's agreed to make the additional changes as mentioned here: https://github.com/ansible-community/collection_migration/issues/128#issuecomment-567269729  I'm not sure if this needs to be re-opened or my original ticket needs to be re-opened to track that.
